### ISSUE TITLE
There is an incompatible JNA native library installed on this system.

### ISSUE THREAD

**Issue by velo** [nebula-plugins/gradle-info-plugin#25]
Got the following error while running on windows:
```
There is an incompatible JNA native library installed on this system.
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the
   jnidispatch library included with the JNA jar file you are using

        at com.sun.jna.Native.<clinit>(Native.java:144)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:42)
        at com.sun.jna.platform.win32.WinBase.<clinit>(WinBase.java:35)
        at com.sun.jna.platform.win32.Kernel32Util.getComputerName(Kernel32Util.java:41)
        at com.sun.jna.platform.win32.Kernel32Util$getComputerName.call(Unknown Source)
        at nebula.plugin.info.ci.UnknownContinuousIntegrationProvider.calculateHost(UnknownContinuousIntegrationProvider.groovy:33)
        at nebula.plugin.info.ci.ContinuousIntegrationInfoProvider$calculateHost$0.call(Unknown Source)
        at nebula.plugin.info.ci.ContinuousIntegrationInfoPlugin$_apply_closure1.doCall(ContinuousIntegrationInfoPlugin.groovy:25)
        at org.gradle.api.internal.ConventionAwareHelper$1.getValue(ConventionAwareHelper.java:72)
        at org.gradle.api.internal.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:136)
        at org.gradle.api.internal.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:114)
        at nebula.plugin.info.ci.ContinuousIntegrationInfoExtension_Decorated.getHost(Unknown Source)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:153)
        at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:107)
        at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:78)
        at nebula.plugin.info.ci.ContinuousIntegrationInfoExtension_Decorated.getProperty(Unknown Source)
        at nebula.plugin.info.ci.ContinuousIntegrationInfoPlugin$_apply_closure5_closure7.doCall(ContinuousIntegrationInfoPlugin.groovy:31)
        at nebula.plugin.info.ci.ContinuousIntegrationInfoPlugin$_apply_closure5_closure7.doCall(ContinuousIntegrationInfoPlugin.groovy)
        at nebula.plugin.info.InfoBrokerPlugin.resolve(InfoBrokerPlugin.groovy:91)
        at nebula.plugin.info.InfoBrokerPlugin.this$2$resolve(InfoBrokerPlugin.groovy)
        at nebula.plugin.info.InfoBrokerPlugin$_collectEntries_closure5.doCall(InfoBrokerPlugin.groovy:71)
        at nebula.plugin.info.InfoBrokerPlugin.collectEntries(InfoBrokerPlugin.groovy:69)
        at nebula.plugin.info.InfoBrokerPlugin.this$2$collectEntries(InfoBrokerPlugin.groovy)
        at nebula.plugin.info.InfoBrokerPlugin$this$2$collectEntries$5.callCurrent(Unknown Source)
        at nebula.plugin.info.InfoBrokerPlugin.buildNonChangingManifest(InfoBrokerPlugin.groovy:59)
        at nebula.plugin.info.InfoBrokerPlugin$buildNonChangingManifest$4.call(Unknown Source)
        at nebula.plugin.info.reporting.InfoJarManifestPlugin$_apply_closure1_closure2_closure3.doCall(InfoJarManifestPlugin.groovy:23)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
        ... 35 more


BUILD FAILED

Total time: 5.989 secs
```

-Djna.nosys=false made no difference

I'm using 2.2.10.

When I tried to upgrade to 3.* got 

```
* What went wrong:
org/gradle/internal/event/BroadcastDispatch
> org.gradle.internal.event.BroadcastDispatch

```

**Comment by DanielThomas** [comment]
We now catch any failure from that call and log a warning. Try upgrading both the plugin, and if you have a compatibility issue, Gradle. If you still have a problem, hit us up on Gitter or on this issue.
