### ISSUE TITLE
Ambiguous method overloading for method java.io.File#<init>.

### ISSUE THREAD

**Issue by p4paul** [nebula-plugins/gradle-info-plugin#64]
If the `P4CONFIG` environment variable is defined (for use with Perforce) I get a Gradle build error (see below for details...). 

Looking at PerforceScmProvider.groovy it seems to be related to another environment variable `WORKSPACE` which was not defined (cause of the null error).  Setting `export WORKSPACE=.` seems to workaround the issue.
 
Using Gradle Wrapper: `gradle-6.1.1-all.zip`

Gradle build error:
```* What went wrong:
A problem occurred configuring root project 'p4search-filter'.
> Failed to notify project evaluation listener.
   > Ambiguous method overloading for method java.io.File#<init>.
     Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
        ...
```

Stack trace:
```Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
        at nebula.plugin.info.scm.PerforceScmProvider.calculateModuleSource(PerforceScmProvider.groovy:23)
        at nebula.plugin.info.scm.PerforceScmProvider$calculateModuleSource.callCurrent(Unknown Source)
```

**Comment by rpalcolea** [comment]
Hi @p4paul,

Thanks for bringing this up

We haven't work with perforce for a while so applied your workaround as default behavior when `WORKSPACE` is missing: https://github.com/nebula-plugins/gradle-info-plugin/pull/65

This was released in [7.1.4](https://github.com/nebula-plugins/gradle-info-plugin/releases/tag/v7.1.4)

Let me know if this is enough or if you have other suggestions for this.
