### ISSUE TITLE
info-scm intermittently fails with large number of subprojects due to JGit bug

### ISSUE THREAD

**Issue by marty-Wallace** [nebula-plugins/gradle-info-plugin#96]
This JGit bug is causing intermittent build failures when attempting to build many subprojects in parallel which all apply the nebula.info plugin. 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=564202

**Reproduction Steps**
This may be difficult to reproduce as it seems to be dependent on timing, I am working in a project with ~17 subprojects and several million LOC and this is still only occurring on ~50% of builds. 

**Fix**
Bump JGit dependency up to or past 5.9.0.202009080501-r
Release Notes show this was fixed in 5.9.0: https://projects.eclipse.org/projects/technology.jgit/releases/5.9.0/ (issue #564202) 

**Workaround**
This workaround is currently resolving the issue for me
```kotlin
constraints {
    implementation("org.eclipse.jgit:org.eclipse.jgit:5.9.0.202009080501-r") {
        because("jgit 5.8 required by nebula has build errors when more than 5 projects build in parallel")
    }
}
```

**Error message** 
```txt
FAILURE: Build completed with 5 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':project:sub:Project Name:writeManifestProperties'.
> Task java.util.concurrent.CompletableFuture$AsyncSupply@2224aa6 rejected from java.util.concurrent.ThreadPoolExecutor@449b3d57[Running, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 0]

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':project:sub:Project Name:writeManifestProperties'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2224aa6 rejected from java.util.concurrent.ThreadPoolExecutor@449b3d57[Running, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 0]
	at org.eclipse.jgit.util.FS$FileStoreAttributes.getFileStoreAttributes(FS.java:329)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.get(FS.java:296)
	at org.eclipse.jgit.util.FS.getFileStoreAttributes(FS.java:767)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:224)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:205)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:102)
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:209)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:583)
	at nebula.plugin.info.scm.GitScmProvider.getRepository(GitScmProvider.groovy:42)
	at nebula.plugin.info.scm.GitScmProvider.calculateModuleSource(GitScmProvider.groovy:64)
	at nebula.plugin.info.scm.GitScmProvider.calculateModuleSource(GitScmProvider.groovy)
	at nebula.plugin.info.scm.AbstractScmProvider.calculateSource(AbstractScmProvider.groovy:38)
	at nebula.plugin.info.scm.ScmInfoProvider$calculateSource.call(Unknown Source)
	at nebula.plugin.info.scm.ScmInfoPlugin$_configureExtMapping_closure3.doCall(ScmInfoPlugin.groovy:79)
	at org.gradle.internal.extensibility.ConventionAwareHelper$1.doGetValue(ConventionAwareHelper.java:69)
	at org.gradle.internal.extensibility.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:128)
	at org.gradle.internal.extensibility.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:110)
	at nebula.plugin.info.scm.ScmInfoExtension_Decorated.getSource(Unknown Source)
	at nebula.plugin.info.scm.ScmInfoPlugin$_apply_closure1$_closure8.doCall(ScmInfoPlugin.groovy:67)
	at nebula.plugin.info.scm.ScmInfoPlugin$_apply_closure1$_closure8.call(ScmInfoPlugin.groovy)
	at nebula.plugin.info.InfoBrokerPlugin.resolve(InfoBrokerPlugin.groovy:165)
        ...
```

**Comment by DanielThomas** [comment]
Thanks for the detailed report @marty-Wallace! We're already using `5.12.0.202106070339-r` internally, don't see any reason why we can't upgrade to the latest 5.x release (`5.13.0.202109080827-r`).

I'll bump the version and roll a minor release now.

**Comment by DanielThomas** [comment]
Release is going out now - https://github.com/nebula-plugins/gradle-info-plugin/releases/tag/v11.2.0

**Comment by marty-Wallace** [comment]
Thanks for the fast turnaround!
